name: "[Workflow] Pull Request"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main


permissions:
  id-token: write
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  fake_tests:
    name: Run fake tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Simulate tests
        run: ./example_file/testing_script.sh
        
  workflow_complete:
    name: End of workflow
    runs-on: ubuntu-latest
    needs: fake_tests
    steps:
      - name: Completion message
        run: echo "Workflow Complete"
