name: "[Workflow] Pull Request"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  workflow_complete:
    name: end of workflow
    runs-on: ubuntu-latest
    steps:
      - name: Completion message
        run: echo "Workflow Complete"
